### ISSUE TITLE
AWS API Gateway compatability

### ISSUE THREAD

**Issue by ivan-m** [GetShopTV/swagger2#113]
FYI: I've just found out from AWS technical support that the reason my generated (from `servant-swagger`) Swagger specification wasn't working was because they don't support the `example` field for objects/models.

It might be worth documenting this.

**Comment by bford-ff** [comment]
I know this is a bit of an old issue, but I've run into something related. I want to add a sections like this (in yaml format) to each of the `paths` in my swagger definition:

```
   x-amazon-apigateway-integration:
        uri: ${servant_lambda_arn}
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" ### NOTE: This has to be POST, regardless of the actual api being get
        type: "aws_proxy"
```

I'm actually generating the whole of the swagger file from a servant API, which I'm deploying to AWS lambda with terraform - having the generated swagger be templated into the terraform set would be awesome. @fizruk @ivan-m - happy to send a PR if necessary or update any documentation if you can point me in the right direction...
