### ISSUE TITLE
Description in ParamSchema

### ISSUE THREAD

**Issue by Martoon-00** [GetShopTV/swagger2#177]
I may be missing something, but why `ParamSchema` does not include a description field?
Swagger2 seems to allow it, and sometimes having a parameter description is really desired.

Example:
```
  /api/v1/animals:
    get:
    ...
      parameters:
      - required: false
        in: query
        name: includeCats
        description: Invade the responses with all kinds of cats.
        type: boolean
```

In the online swagger editor that description is rendered fine:

![screenshot from 2019-01-30 17-59-11](https://user-images.githubusercontent.com/5394217/51989764-c9d0d680-24b8-11e9-9be3-dea2e6ef1f4c.png)
